# Generated by Django 6.1 on 2026-09-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del proveedor (Ej. AWS, Hostinger)')),
                ('contacto', models.CharField(max_length=100, verbose_name='Nombre de contacto')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del servicio/producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('hosting', 'Infraestructura y Hosting'), ('desarrollo', 'Desarrollo Web / Apps'), ('licencias', 'Licencias de Software'), ('soporte', 'Horas de Soporte / Mantenimiento')], max_length=50, verbose_name='Categoría')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock actual (Capacidad disponible)')),
                ('stock_minimo', models.IntegerField(default=0, verbose_name='Stock mínimo (Punto de reorden)')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='scm.proveedor', verbose_name='Proveedor de infraestructura')),
            ],
            options={
                'verbose_name': 'Producto / Servicio',
                'verbose_name_plural': 'Productos / Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
