# Generated by Django 6.1 on 2026-09-19 10:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10, verbose_name='Tipo de movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('motivo', models.CharField(choices=[('venta', 'Venta de Proyecto / Contratación'), ('liberacion', 'Liberación de Recursos / Proyecto Terminado'), ('reposicion', 'Reposición / Aumento de Capacidad'), ('ajuste', 'Ajuste Manual')], max_length=20, verbose_name='Motivo')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del movimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='scm.producto', verbose_name='Servicio / Producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
