# Generated by Django 6.1 on 2026-09-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0002_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estrategia',
            field=models.CharField(choices=[('PUSH', 'PUSH (Producción/compra anticipada)'), ('PULL', 'PULL (Según demanda real)')], default='PUSH', max_length=10, verbose_name='Estrategia Logística'),
        ),
    ]
