# Generated by Django 6.1 on 2026-09-19 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0003_producto_estrategia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Folio')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('tipo', models.CharField(choices=[('Reposicion', 'Reposición'), ('Venta', 'Venta'), ('Ajuste', 'Ajuste')], default='Reposicion', max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Surtido', 'Surtido'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.producto', verbose_name='Servicio / Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='scm.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
