# Generated by Django 6.1 on 2026-08-29 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del contacto')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('empresa', models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa / Negocio')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado')),
                ('etapa_crm', models.CharField(choices=[('prospecto', 'Prospecto'), ('activo', 'Activo'), ('frecuente', 'Frecuente'), ('inactivo', 'Inactivo')], default='prospecto', max_length=15, verbose_name='Etapa CRM')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('correo', 'Correo'), ('reunion', 'Reunión')], max_length=10, verbose_name='Tipo de interacción')),
                ('descripcion', models.TextField(verbose_name='Descripción / Minuta')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de interacción')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='crm.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
